import { AppShell } from "@/components/app-shell";
import { currentDemonstrationEmployee } from "@/lib/authorization";
import { decideExpense, decideSale } from "@/app/actions";
import { recordsFor } from "@/lib/data";
import { euros } from "@/lib/finance";

export default async function ApprovalsPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const employee = await currentDemonstrationEmployee(); const message = await searchParams; const records = employee?.role === "manager" ? await recordsFor(employee) : null;
  return <AppShell employee={employee}><section className="page-lead"><p className="eyebrow">Manager workflow</p><h2>Approvals and corrections</h2><p className="muted">Final decisions preserve the submitted proposal. Repeated approvals are denied by the server.</p></section>{message.error && <p className="error">{message.error}</p>}{message.success && <p className="success">{message.success}</p>}
    {!records ? <p className="locked">Only Svetlana can inspect or decide approvals. This is enforced in the server action.</p> : <><h3>Sales awaiting approval</h3>{records.sales.filter((sale) => sale.status === "pending_approval").length === 0 ? <p className="empty">No pending sales.</p> : records.sales.filter((sale) => sale.status === "pending_approval").map((sale) => <article className="decision" key={sale.id}><h3>{sale.reference} — {sale.customer}</h3><p>{sale.description}<br />Project {sale.project} · {euros(sale.amount)}</p><p className="muted">Original proposed split: Richard {sale.proposed_richard_percentage}% · Anastasia {sale.proposed_anastasia_percentage}% · Jean-Claude {sale.proposed_jean_claude_percentage}%</p><form action={decideSale} className="inline-form"><input type="hidden" name="saleId" value={sale.id} /><label>Richard %<input name="richard" type="number" min="0" max="100" step="0.01" defaultValue={sale.proposed_richard_percentage} required /></label><label>Anastasia %<input name="anastasia" type="number" min="0" max="100" step="0.01" defaultValue={sale.proposed_anastasia_percentage} required /></label><label>Jean-Claude %<input name="jeanClaude" type="number" min="0" max="100" step="0.01" defaultValue={sale.proposed_jean_claude_percentage} required /></label><button className="primary">Approve sale</button></form></article>)}
    <h3>Expenses awaiting allocation</h3>{records.expenses.filter((expense) => expense.status === "awaiting_allocation").length === 0 ? <p className="empty">No pending expense allocations.</p> : records.expenses.filter((expense) => expense.status === "awaiting_allocation").map((expense) => <article className="decision" key={expense.id}><h3>{expense.reference} — {euros(expense.amount)}</h3><p>{expense.description} · {expense.category}</p><p className="muted">Original proposed allocation: {expense.proposed_allocation.replace("_", " ")}</p><form action={decideExpense} className="inline-form"><input type="hidden" name="expenseId" value={expense.id} /><label>Final allocation<select name="allocation" defaultValue={expense.proposed_allocation}><option value="A">A — Respectable Relatives</option><option value="B">B — Drunk University Friends</option><option value="company_overhead">Company overhead</option></select></label><button className="primary">Confirm allocation</button></form></article>)}</>}</AppShell>;
}
